### ISSUE TITLE
Reopen of #366

### ISSUE THREAD

**Issue by aski71** [iobroker-community-adapters/ioBroker.ical#403]
https://github.com/iobroker-community-adapters/ioBroker.ical/issues/366

I was able to reproduce.

- Event entered into Calender at 19:45 with start time 20:15 today
- iCal fetches event at 20:00 correctly, shows it at "later"
- Event stays in "later" until 20:30 and is only then moved to "now"

Is this a works as designed and granularity of events being covered is :00 and :30 only?
Or is this a bug?
I'd consider it as bug.

Thanks, Alex

**Comment by Apollon77** [comment]
Then please provide a debug log of such a case. Thank you

**Comment by Wildbill-Z** [comment]
I think, I have the same problem and I think it is "by design".
I have set ical-adapter to 

`1 * * * *
`
so every minute after a full hour it restarts and checkes for new events. If I have an event that starts 18:00 the datapoint "now" in objects is set to true at 18:01. So it seems that only at restart (cron or manual) the events in objects are updated.
As I said, I think this is by design as the ical-adapter isn`t running all the time but only at periods set via cron.
So I thin @aski71 has set cron for ical to 

`0,30 * * * *
`
which restarts every 30 minutes and so event-now only gets updated and set to true at xx:00 or xx:30 but not between.

**Comment by Apollon77** [comment]
Yes ... states can only change values if someone sets them ... when you set the adapter to this hourly schedule then you will also get only updates once an hour. So yes it is by design.

If you need it updated more often change the schedule.
